### ISSUE TITLE
Make github releases

### ISSUE THREAD

**Issue by petarGitNik** [owkin/charts#16]
**What would you like to be added**:

Can you make GitHub releases also? Helm hub does not have any subscription, so it's hard to track latest versions of the chart.

**Why is this needed**:

If you make releases on GitHub, anyone can user "Watch" option to track new releases of the chart.

**Comment by ClementGautier** [comment]
@petarGitNik The issue is that this repository is a meta-repository that could contain more than one chart in the future. Having to tag this repo doesn't really make sense. The workaround could be to put the pypiserver chart in a dedicated repository (and maybe make a subtree split to keep this meta package as a helm repo). There is no actual roadmap regarding that tho

**Comment by petarGitNik** [comment]
@ClementGautier Thanks! Yes, I know, the whole structure of Helm chart repos is kinda awkward. SonarQube has several different charts and they tag releases, but then I get overwhelmed by charts I don't really need. I'll implement "healm search <chart>" and parse for a new version. That is probably more scalable solution to being updated on various charts. Thank you for considering, but I wouldn't suggest modifying anything with subtrees and meta packages. I'll close this since I found the solution in the meantime :) thank you :+1:
